### ISSUE TITLE
Fill and Fit video transformation

### ISSUE THREAD

**Issue by novachevskyi** [linkedin/LiTr#218]
It looks to be not really obvious how to transform video size to Fill or Fit the new requested frame size. Will appreciate any guidance on how it's possible to do that in a proper way.

For example, I have a video with the following params:
```
sourceWidth = 2160
sourceHeight = 3840
rotation = -0.0
```

and I'm willing to transform it to the following size and fill the frame:
```
width = 1080
height = 592
```

This code will work for me:
```
Transform(
  PointF(1 + sourceWidth.toFloat() % width, (sourceHeight.toFloat() / height) / (sourceWidth / width)),
  PointF(0.5f, 0.5f),
  rotation,
)
```

However, the same logic won't work for:
```
sourceWidth = 720
sourceHeight = 1280
rotation = -90.0
```

Even assuming we are rotating the video from 90 to 0 degrees I've tried to replace x with y, but still no luck. The frame is being stretched.

There are many different scenarios of transformation I need to handle such:
- Square video (FILL/FIT)
- Portrait video 16/9 (FILL/FIT)
- Landscape video 9/16 (FILL/FIT)
- Original video size (FILL/FIT) where initial size is determined by the first uploaded video.
All these options could be applied for video sets with different video sizes, so I need some generic logic here to calculate the final transformation.

**Comment by novachevskyi** [comment]
@izzytwosheds Sorry if I was being unclear here, but now I think I can share more specific details.
To convert the video to the desired size I used this conversion logic: https://github.com/MasayukiSuda/Mp4Composer-android/blob/84b20be5218af7da25f2523bed5c19c482325518/mp4compose/src/main/java/com/daasuu/mp4compose/FillMode.java

Using `getScaleAspectCrop` specifically to make the video Fill into the new frame size.

So the logic works fine when the initial video rotation is 0 and there is no need to rotate it. However, if the initial video rotation is being set to 90 degrees then I'm rotating the video via Transformation to -90 degrees and the output is being stretched in the wrong way.

I'm wondering if there is a simple way to make the rotation first and then apply size transformation for the specific video. Do you have some thoughts?

Sorry if I'm still not 100% clear, still digging into it. But I feel the logic behind transformation with rotation doesn't work as expected.

**Comment by novachevskyi** [comment]
My transformation code looks like this:
```
val scaleCalc =
              fillMode.getScaleAspectCrop(videoRotation, sourceFormat.width, sourceFormat.height, width, height)
Transform(
  PointF(scaleCalc[0], scaleCalc[1]),
  PointF(0.5f, 0.5f),
  rotation,
)
```

**Comment by novachevskyi** [comment]
This [video](https://drive.google.com/file/d/1EeyrYbhaCV-hu24FhIyEEwiMl3xDtRzd/view?usp=sharing) works fine with the mentioned code since it has 0 degree initial rotation, so I'm not rotating it within `Transform`.

The video with the following params:
```
sourceWidth = 2160
sourceHeight = 3840
rotation = 0.0
```

and I'm willing to transform it to the following size and fill the frame (16/9 ratio to make it landscape from the portrait):
```
width = 1080
height = 592
```

**Comment by novachevskyi** [comment]
This [video](https://drive.google.com/file/d/1-k1QqLecVHEDr4NZ0F-cvvYxKrPgZ0v4/view?usp=sharing) with:
```
sourceWidth = 768
sourceHeight = 1024
rotation = 90.0
```
goal (portrait -> landscape 16/9):
```
width = 768
height = 432
```

**Comment by izzytwosheds** [comment]
let me look at these. Thank you for sharing specific examples. 
Just to clarify, you are using 'DefaultVideoFrameRenderFilter`, right?

**Comment by novachevskyi** [comment]
@izzytwosheds correct, everything is tested with `DefaultVideoFrameRenderFilter`

**Comment by novachevskyi** [comment]
The output looks like this. However, if I'll take the same video being already rotated then the transformation logic will work fine.
![Screenshot_20220927_143538](https://user-images.githubusercontent.com/2072831/192515019-9f6f0d9c-eaa2-4eed-911d-3878b4833dd4.png)

**Comment by izzytwosheds** [comment]
One important point: `rotation` in `DefaultFrameRenderFilter` is not a rotation of target video frame, it is a rotation of source video frame relative to target video frame. Orientation (rotation) of target frame is provided via target `MediaFormat`. It is a little confusing, I know. 

Let's talk about target video frame first. 

Landscape video is usually defined like this:
width = 1280
height = 720
rotation = 0

Portrait video is defined like this:
width = 720
height = 1280
rotation = 0
OR
width = 1280
height = 720
rotation = 90

Second way is more common - you change video orientation simply by changing 4 bytes instead of recalculating entire video. 

LiTr accounts for target frame orientation, there is nothing special you have to do there. Just make your size calculations based on frame rectangle. You can treat orientation of 90 as if frame has a portrait aspect ratio - LiTr will adjust all parameter you pass in.

Now to source frame. 

In `Transform` your `rotation` is always `0`, unless you specifically want to rotate your frame. 
For FILL `position` is always (0.5, 0.5) and scale is (1.0, 1.0). Those are default values, you can pass no `DefaultVideoFrameRenderTransform` entirely, LiTr should just scale fit your source frame into target frame. 

For FIT you will have to play around with `position`. See [TransformationPresenter.squareCenterCrop](https://github.com/linkedin/LiTr/blob/main/litr-demo/src/main/java/com/linkedin/android/litr/demo/data/TransformationPresenter.java#L293) method. It stretches the source frame beyond the bounds of target frame.

**Comment by izzytwosheds** [comment]
Come to think of it, FIT transformation I described above is actually CROP. For FIT largest `scale` parameter would be 1, entire source frame would have to stay within the target frame. `position` and `rotation` parameters would stay the same, though.

**Comment by novachevskyi** [comment]
@izzytwosheds thanks for the explanation! I guess it works for me when I'm setting rotation to 0 in the target track object. I'll keep testing and will let you know if something won't work as expected.

**Comment by izzytwosheds** [comment]
@novachevskyi Are things working well for you? Can we close this issue?

**Comment by novachevskyi** [comment]
Yes, please close it.
